name: ThunderHeart Ceremonies
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9813567968085408
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e3e2'
    - '#1f2740'
    - '#a6aebd'
    - '#665550'
    - '#b2687d'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
